#	$OpenBSD: Makefile,v 1.10 2010/01/04 17:50:36 deraadt Exp $
#
# C Shell with process control; VM/UNIX VAX Makefile
# Bill Joy UC Berkeley; Jim Kulp IIASA, Austria
#
# To profile, put -DPROF in DEFS and -pg in CFLAGS, and recompile.

PROG=	csh
DFLAGS=-DBUILTIN -DFILEC -DNLS -DSHORT_STRINGS
#CFLAGS+=-g
#CFLAGS+=-Wall
CFLAGS+=-z muldefs -I${PREFIX}/include -L${PREFIX}/lib -L/system/lib ${DFLAGS}
SRCS=	alloc.c char.c const.c csh.c dir.c dol.c error.c exec.c exp.c file.c \
	func.c glob.c hist.c init.c lex.c misc.c parse.c proc.c \
	sem.c set.c str.c time.c

CLEANFILES=*.o csh

all:
	${CC} -o ${PROG} ${CFLAGS} -DBIONIC ${SRCS} -lbsd -landroid-glob -lc

clean:
	rm -f ${CLEANFILES}

install:
	install -p csh ${PREFIX}/bin/
	gzip -c csh.1 > ${PREFIX}/share/man/man1/csh.1.gz

const.h: error.h

error.h: error.c
	@rm -f $@
	@echo '/* Do not edit this file, make creates it. */' > $@
	@echo '#ifndef _h_sh_err' >> $@
	@echo '#define _h_sh_err' >> $@
	egrep 'ERR_' *.c | egrep '^#define' >> $@
	@echo '#endif /* _h_sh_err */' >> $@

const.h: const.c
	@rm -f $@
	@echo '/* Do not edit this file, make creates it. */' > $@
	${CC} -E ${CFLAGS} *.c | egrep 'Char STR' | \
	    sed -e 's/Char \([a-zA-Z0-9_]*\)\(.*\)/extern Char \1[];/' | \
	    sort >> $@

.depend alloc.o: const.h error.h 
