# Makefile for csh
PROG = csh
CC = gcc
OPT = -O2

CFLAGS = -c \
	 -Wall \
	 -DNLS=1 \
	 -DSHORT_STRINGS=1

ostype = `uname -s`
ifeq ($(ostype),Linux)
	CFLAGS = $(CFLAGS) \
		 -D_GNU_SOURCE=1 \
		 `pkg-config --cflags libbsd-overlay`
endif

LIBS =
ifeq ($(ostype),Linux)
	LIBS = -lbsd
endif

SRC = alloc.c \
      char.c \
      const.c \
      csh.c \
      dir.c \
      dol.c \
      err.c \
      exec.c \
      exp.c \
      func.c \
      glob.c \
      hist.c \
      init.c \
      lex.c \
      misc.c \
      parse.c \
      proc.c \
      sem.c \
      set.c \
      str.c \
      time.c
OBJ = $(SRC:.c=.o)

all: const.h $(OBJ)
	$(CC) -o $(PROG) $(OBJ) $(LIBS)
	strip ./$(PROG)

%.o: %.c
	$(CC) $(OPT) $(CFLAGS) $<

clean: 
	rm -f errnum.h const.h ./*.o ./$(PROG)

errnum.h: err.c
	( echo '/* Do not edit this file, make creates it. */' ; \
	echo '#ifndef _h_sh_errnum' ; \
	echo '#define _h_sh_errnum' ; \
	egrep 'ERR_' $(SRC) | egrep '^#define' ; \
	egrep 'ERR_' $(PWD)/*.[ch] | egrep '#define' | \
	sed -e 's/.*#define/#define/' ; \
	echo '#endif /* _h_sh_errnum */' ) > $@

const.c: errnum.h
const.h: const.c
	echo '/* Do not edit this file, make creates it. */' > $@
	$(CC) -E $(CFLAGS) $(PWD)/*.[ch] | egrep 'Char STR' | \
	sed -e 's/Char \([a-zA-Z0-9_]*\)\(.*\)/extern Char \1[];/' \
	-e 's/.*extern/extern/' | sort >> $@
